In [2]:
# ##### Statistical Functions

# `NumPy` provides built-in methods to compute statistics like mean, sum, and standard deviation.


In [3]:

import numpy as np
data = np.array([[80, 85, 90],
                 [70, 75, 65],
                 [88, 92, 95]])

print("Mean:", np.mean(data))
print("Sum:", np.sum(data))

axis1 = np.mean(data, axis=1) # Mean across rows
print("Mean across rows (axis=1):", axis1)

axis0 =np.mean(data, axis=0) # Mean across columns
print("Mean across columns (axis=0):", axis0)
print("Standard Deviation:", np.std(data))
print("Max of data:", np.max(data) )
print("Min of data:", np.min(data) )




Mean: 82.22222222222223
Sum: 740
Mean across rows (axis=1): [85.         70.         91.66666667]
Mean across columns (axis=0): [79.33333333 84.         83.33333333]
Standard Deviation: 9.795438595792973
Max of data: 95
Min of data: 65


In [4]:
student1_mean = np.mean(data[0])
print("Mean of student 1:", student1_mean)

student2_mean = np.mean(data[1])
print("Mean of student 2:", student2_mean)

student3_mean=np.mean(data[2])
print("Mean of student 3:",student3_mean)

Mean of student 1: 85.0
Mean of student 2: 70.0
Mean of student 3: 91.66666666666667


In [5]:
#mean for 2nd and 3rd student in same
mean_2_3 = np.mean(data[1:3], axis=1)
print("Mean of student 2 and 3:", mean_2_3)



Mean of student 2 and 3: [70.         91.66666667]


In [6]:
# ##### Boolean Indexing & Filtering

# - Use boolean masks to filter arrays based on conditions.

# - In NumPy, you can pass a boolean array inside square brackets to filter the original array. This is called boolean indexing.

In [7]:
scores = np.array([55, 72, 89, 45, 99, 66, 78])
high_scores = scores[scores > 70]
print("Scores > 70:", high_scores)

# Find even scores
even_scores = scores[scores % 2 == 0]
print("Even Scores:", even_scores)

# Find scores between 60 and 80
mid_scores = scores[(scores >= 60) & (scores <= 80)]
print("Scores between 60 and 80:", mid_scores)

Scores > 70: [72 89 99 78]
Even Scores: [72 66 78]
Scores between 60 and 80: [72 66 78]


In [8]:
high = data[data > 70]
print("high scores 2D array:", high)

high scores 2D array: [80 85 90 75 88 92 95]


In [9]:
type(high)

numpy.ndarray

In [10]:
#matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result1 = np.dot(mat1, mat2)
print("Matrix Multiplication:\n",result1)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [11]:
mat1 = np.array([[1, 2], [3, 4] ,[5,6]])
mat2 = np.array([1,3])
result1 = np.dot(mat1,mat2)
print("Matrix Multiplication:\n",result1)




Matrix Multiplication:
 [ 7 15 23]


In [12]:
import numpy as np
np.random.seed(42)
student_scores = np.random.randint(50, 100, size=(5, 4))

print("All Scores:\n", student_scores)
print("-" * 20)

print("Averages:", np.mean(student_scores, axis=1))
print("-" * 20)

# Logic: If a student's MAX score is > 75, keep that row.
print("Students > 75:\n", student_scores[np.max(student_scores, axis=1) > 75])

All Scores:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]
--------------------
Averages: [80.5  70.75 66.25 74.75 72.  ]
--------------------
Students > 75:
 [[88 78 64 92]
 [57 70 88 68]
 [85 89 73 52]
 [71 51 73 93]]


In [13]:
# ## Assignment: Analyze Numeric Data and Filter Top 10% Scores

# Given a list of exam scores for 30 students, write a program to:
# - Compute the mean and standard deviation
# - Filter scores in the top 10%

import numpy as np

np.random.seed(42)

# 30 random scores between 50 and 100
scores = np.random.randint(50, 101, 30)

print("Scores:", scores)




Scores: [88 78 64 92 57 70 88 68 72 60 60 73 85 89 73 52 71 51 73 93 79 87 51 70
 82 61 71 93 74 98]


In [14]:
mean = np.mean(scores)
std_dev = np.std(scores)

print("Mean:", mean)
print("Standard Deviation:", std_dev)



Mean: 74.1
Standard Deviation: 13.189263310233315


In [15]:
top_10 = np.sort(scores)[-3:]
print("Top 10% Scores:", top_10)


Top 10% Scores: [93 93 98]
