In [204]:
import numpy as np
import time



In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [206]:
a = list(range(1000000))
b = list(range(1000000))

start = time.time()
result = [x + y for x, y in zip(a, b)]
end = time.time()
print("Python List Time:", end - start)

Python List Time: 0.048333168029785156


In [207]:
a_np = np.arange(1000000)
b_np = np.arange(1000000)

start = time.time()
result_np = a_np + b_np
end = time.time()
print("NumPy Array Time:", end - start)

NumPy Array Time: 0.0013082027435302734


In [208]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [209]:
a = np.array([1, 2, 3])
print("1D Array:", a)
a.shape

1D Array: [1 2 3]


(3,)

In [210]:
a= np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", a)
a.shape

2D Array:
 [[1 2 3]
 [4 5 6]]


(2, 3)

In [211]:
b =np.zeros(3)
print("Zeros:\n", b)

Zeros:
 [0. 0. 0.]


In [212]:
b =np.zeros((2, 3))
print("Zeros Array:\n", b)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [213]:
b =np.zeros((4, 5))
print("Zeros:\n", b)

Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [214]:
c=np.ones((5))
print("Ones:\n", c)

Ones:
 [1. 1. 1. 1. 1.]


In [215]:
c=np.ones((3, 4), dtype=int)
print("Ones:\n", c)

Ones:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [216]:
type(c)

numpy.ndarray

In [217]:
d=np.arange(10)
print("Arrange:\n", d)

Arrange:
 [0 1 2 3 4 5 6 7 8 9]


In [218]:
# #### Slicing and Reshaping Arrays

# * Slicing helps extract parts of arrays.
# * Reshaping changes the shape without changing data.

In [219]:
import numpy as np

arr = np.arange(12)
print("Original:", arr)

#Slicing
print("First 5:", arr[:5])
print("Last 3:", arr[-3:])
arr.shape

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
First 5: [0 1 2 3 4]
Last 3: [ 9 10 11]


(12,)

In [220]:
arr.ndim

1

In [221]:
reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

print("\nLast column:", reshaped[:, -1])
print("First two rows:\n", reshaped[:-1])

reshaped[0][-1]=55
arr.ndim

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Last column: [ 3  7 11]
First two rows:
 [[0 1 2 3]
 [4 5 6 7]]


1

In [222]:
reshaped[1,1]


np.int64(5)

In [223]:
reshaped[0, -1] = 55


In [224]:
reshaped

array([[ 0,  1,  2, 55],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
reshaped.ndim

2

In [226]:
reshaped_arr = arr.reshape((3, 4))
print("Reshaped (3x4):\n", reshaped_arr)
reshaped_arr
reshaped_arr[2, 3]
reshaped_arr[2, 3] = 99
reshaped_arr



Reshaped (3x4):
 [[ 0  1  2 55]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2, 55],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 99]])

In [227]:
reshaped_arr.shape

(3, 4)

In [228]:
reshaped_arr.ndim

2

In [229]:
maximum = np.max(reshaped_arr)
print("Maximum value:", maximum)


Maximum value: 99


In [230]:
minimum = np.min(reshaped_arr)
print("Minimum value:", minimum)


Minimum value: 0


In [231]:
# ##### Vectorized Operations & Broadcasting

# * `Vectorized operations` allow fast element-wise operations.
# * `Broadcasting` enables operations between arrays of different shapes.

In [259]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Addition:", x + y)
print("Multiplication:", x * y)
print("Scalar Multiplication:", x * 10)

mat = np.ones((2,3), dtype=int)
print( mat)


print("-------")
vec = np.array([1, 2, 3])

add= mat + vec
mul=mat @ vec

print("Broadcasted Multiplication:\n", mat @ vec)


print("Broadcasted Addition:\n", mat + vec)
add.shape
mul.shape



Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multiplication: [10 20 30]
[[1 1 1]
 [1 1 1]]
-------
Broadcasted Multiplication:
 [6 6]
Broadcasted Addition:
 [[2 3 4]
 [2 3 4]]


(2,)